const EMAIL_CHANGED = 'EMAIL_CHANGED';
const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
const LOGIN_USER_START = 'LOGIN_USER_START';
const SAVE_INFO = 'SAVE_INFO';
const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';
const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';

export {
    EMAIL_CHANGED,
    PASSWORD_CHANGED,
    LOGIN_USER_SUCCESS,
    LOGIN_USER_ERROR,
    LOGIN_USER_START,
    SAVE_INFO,
    SAVE_EMPLOYEE,
    FETCH_EMPLOYEE_SUCCESS
};
